name: Generate CV

env:
  PDF_FILE_PT: "cv-jmpvr-pt.pdf"
  DOC_FILE_PT: "cv-jmpvr-pt.docx"
  MD_FILE_PT: "cv-jmpvr-pt.md"
  PDF_FILE_EN: "cv-jmpvr-en.pdf"
  DOC_FILE_EN: "cv-jmpvr-en.docx"
  MD_FILE_EN: "cv-jmpvr-en.md"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "cv-jmpvr-pt.pdf"
      - "cv-jmpvr-pt.docx"
      - "cv-jmpvr-en.pdf"
      - "cv-jmpvr-en.docx"

jobs:
  generate:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
          pip install python-docx==1.1.2

      - name: Convert Markdown to PDF
        run: |
          pandoc ${{ env.MD_FILE_PT }} -o ${{ env.PDF_FILE_PT }} --pdf-engine=pdflatex && \
          pandoc ${{ env.MD_FILE_EN }} -o ${{ env.PDF_FILE_EN }} --pdf-engine=pdflatex

      - name: Create compact reference DOCX
        run: |
          pandoc --print-default-data-file reference.docx > reference.docx
          python3 create_reference_doc.py

      - name: Convert Markdown to DOCX
        run: |
          pandoc ${{ env.MD_FILE_PT }} -o ${{ env.DOC_FILE_PT }} --reference-doc=reference.docx && \
          pandoc ${{ env.MD_FILE_EN }} -o ${{ env.DOC_FILE_EN }} --reference-doc=reference.docx

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain ${{ env.PDF_FILE_PT }} ${{ env.DOC_FILE_PT }} ${{ env.PDF_FILE_EN }} ${{ env.DOC_FILE_EN }})" ]; then
            echo "files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "files_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.PDF_FILE_PT }} ${{ env.DOC_FILE_PT }} ${{ env.PDF_FILE_EN }} ${{ env.DOC_FILE_EN }}
          git commit -m "Update generated CV files [skip ci]"
          git push
